### ISSUE TITLE
Unable to access catalog on browser

### ISSUE THREAD

**Issue by ElodieFZ** [metno/S-ENDA-csw-catalog-service#11]
When working with localdev VM and the Docker container to run the catalog, starting the webserver seens to work:

> 
pycsw@6e44bb56bd69:~/mmd/bin$ python3 /usr/local/bin/entrypoint.py
DEBUG:__main__:Setting up pycsw's data repository...
DEBUG:__main__:Repository URL: sqlite:////home/pycsw/tests.db
DEBUG:__main__:Launching pycsw with gunicorn --bind=0.0.0.0:8000 --access-logfile=- --error-logfile=- --workers=2 pycsw.wsgi ...
[2020-11-17 07:13:17 +0000] [40] [INFO] Starting gunicorn 20.0.4
[2020-11-17 07:13:17 +0000] [40] [INFO] Listening at: http://0.0.0.0:8000 (40)
[2020-11-17 07:13:17 +0000] [40] [INFO] Using worker: sync
[2020-11-17 07:13:17 +0000] [44] [INFO] Booting worker with pid: 44
[2020-11-17 07:13:17 +0000] [45] [INFO] Booting worker with pid: 45

But I am unable to access the catalog on a browser (tried with Chrome / Firefox / Lynx):

> This site can’t be reached10.20.0.30 took too long to respond.

Pinging from a terminal works:

> 

(base) ~/Work/metno_repos/S-ENDA-csw-catalog-service (issues_5_and_7_old_git_repo__and__failing_build) $ ping 10.20.30.11
PING 10.20.30.11 (10.20.30.11) 56(84) bytes of data.
64 bytes from 10.20.30.11: icmp_seq=1 ttl=64 time=0.285 ms
64 bytes from 10.20.30.11: icmp_seq=2 ttl=64 time=0.233 ms
64 bytes from 10.20.30.11: icmp_seq=3 ttl=64 time=0.187 ms
64 bytes from 10.20.30.11: icmp_seq=4 ttl=64 time=0.187 ms

**Comment by ElodieFZ** [comment]
@aheimsbakk - could you help here?

**Comment by mortenwh** [comment]
I'm closing this one since it started to work now :)
