### ISSUE TITLE
Storage on thredds.met.no + OPeNDAP streaming

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-csw-catalog-service#21]

**Comment by ferrighi** [comment]
Check configuration of thredds and see if data are available as OPeNDAP stream.

**Comment by TAlonglong** [comment]
There is an coffee info Thursday 11 with topic:

Gaute holde foredrag om DARS.

A fast and light OPeNDAP server

Vel møtt via MEET
meet.google.com/zzv-gcoe-psn

We need to figure out how this is related to thredds opendap

See also https://github.com/gauteh/dars

**Comment by TAlonglong** [comment]
I think this is mostly done now.
