### ISSUE TITLE
Integration with GeoNorge and NINA

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-csw-catalog-service#24]

**Comment by ferrighi** [comment]
Check what is the output profile needed for GeoNorge and NINA

**Comment by mortenwh** [comment]
I'll try to set up a meeting with Lars-Inge Arnevik at Kartverket!

**Comment by mortenwh** [comment]
So this will be on Friday at 10:30 :)

**Comment by ferrighi** [comment]
Should we close this @mortenwh ? we had a meeting with both now.

**Comment by mortenwh** [comment]
yes :)
