### ISSUE TITLE
Support WMO ISO profile

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-csw-catalog-service#29]
CSW is currently only supporting one iso profile, which is the one used to index the records. 
Addition of new profiles should be addressed to support WMO iso and INSPIRE iso

- [ ] Open issue on pyCSW repository asking for new output schema

The following output schema should be added:

- [ ] WMO core profile (WIS)

The following mapping(s) should be made

- [ ] Add mapping between GeoNorge INSPIRE and WIS

**Comment by aheimsbakk** [comment]
Repo will be archived. Closing issue.
